[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["/webull_service/**", "/migrations/**", "/requirements.txt", "/Dockerfile"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
